Backend content object tree selector
Fysiksektionen/Hemsida pull request #52
Opened 2021-03-24 00:45 UTC by Ejemyr

Created selector that gets a content_object-tree

In this PR:
- Selector that builds tree in minimal number of queries. (main)
- Tests for the selector
- Added parent_page to ContentObjectBase so that each content Object is connected to a ContentObject.
- Fixed bugs found in testing code of pages.
- Removed the SortableMixin from ContentObjects

2021-04-08 17:41 UTC, fridaagronberg commented on server/website/models/content_objects.py
> +    parent_page = models.ForeignKey(
Döpa om pga lite förvirrande

2021-04-08 18:02 UTC, fridaagronberg requested changes
Tycker parent_page borde döpas om, annars ser det bra ut:)

2021-04-11 14:10 UTC, Ejemyr commented
Fixat att döpa om `parent_page`. Heter nu `containing_page`. Denna PR borde gå att merga nu.

2021-04-11 14:14 UTC, fridaagronberg approved these changes

2021-04-11 14:14 UTC, merged